import React, { useState, useEffect } from 'react';
import {
  Container, Typography, Box, Table, TableBody, TableCell, TableContainer, TableHead, 
  TableRow, Paper, Button, TextField, CircularProgress, Alert, Grid, Card, CardContent, Stack
} from '@mui/material';
import PictureAsPdfIcon from '@mui/icons-material/PictureAsPdf';
import DateRangeIcon from '@mui/icons-material/DateRange';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import api from '../../api';
import { useAuth } from '../../context/AuthContext';
import { theme } from '../../theme';
import { branding } from '../../config/branding';

function AdminReportsPage() {
  const [orders, setOrders] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  
  // Date Filters
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');

  const { userInfo } = useAuth();
  
  // Get Today's Date for "max" attribute (Item #24)
  const today = new Date().toISOString().split('T')[0];
  
  useEffect(() => {
    const fetchOrders = async () => {
      setLoading(true);
      try {
        const { data } = await api.get('/api/orders');
        // Only show active orders (exclude Cancelled) for actual sales revenue
        // If you want to show ALL (including cancelled), remove this filter.
        setOrders(data.filter(o => o.status !== 'Cancelled')); 
      } catch (err) {
        setError(err.response?.data?.message || err.message);
      } finally {
        setLoading(false);
      }
    };
    fetchOrders();
  }, []);

  // --- QUICK FILTERS (Item #12) ---
  const handleQuickFilter = (type) => {
      const now = new Date();
      let start = new Date();
      let end = new Date();

      if (type === 'today') {
          // Start and End are today
      } else if (type === 'week') {
          // Start of week (Sunday)
          const day = now.getDay();
          const diff = now.getDate() - day; 
          start.setDate(diff);
          end.setDate(start.getDate() + 6);
      } else if (type === 'month') {
          start = new Date(now.getFullYear(), now.getMonth(), 1);
          end = new Date(now.getFullYear(), now.getMonth() + 1, 0); // Last day of month
      } else if (type === 'year') {
          start = new Date(now.getFullYear(), 0, 1);
          end = new Date(now.getFullYear(), 11, 31);
      }

      setStartDate(start.toISOString().split('T')[0]);
      setEndDate(end.toISOString().split('T')[0]);
  };

  const getFilteredOrders = () => {
      return orders.filter(order => {
          // Normalize dates to YYYY-MM-DD for comparison
          const orderDate = new Date(order.createdAt).toISOString().split('T')[0];
          const start = startDate || '0000-01-01';
          const end = endDate || '9999-12-31';
          return orderDate >= start && orderDate <= end;
      });
  };

  const filteredOrders = getFilteredOrders();
  const totalSales = filteredOrders.reduce((acc, curr) => acc + curr.totalPrice, 0);

  // --- PDF GENERATOR FUNCTION (Item #11) ---
  const generatePDF = () => {
    const doc = new jsPDF();
    
    // --- 1. HEADER ---
    doc.setFillColor(237, 108, 2); // Brand Orange
    doc.rect(0, 0, 210, 20, 'F'); // Orange top bar
    
    doc.setFontSize(22);
    doc.setTextColor(255, 255, 255);
    doc.text(branding.name.toUpperCase(), 14, 13);
    
    doc.setFontSize(10);
    doc.text("Sales & Revenue Report", 160, 13);

    // --- 2. REPORT INFO ---
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.text(`Generated By: ${userInfo?.name || 'Admin'}`, 14, 30);
    doc.text(`Date Generated: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, 14, 35);
    
    doc.text(`Period Covered: ${startDate || 'All Time'} to ${endDate || 'Present'}`, 14, 45);

    // --- 3. SUMMARY BOX ---
    doc.setDrawColor(200);
    doc.setFillColor(245, 245, 245);
    doc.roundedRect(14, 50, 180, 25, 3, 3, 'FD');
    
    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text("Total Orders", 25, 60);
    doc.text("Total Revenue", 100, 60);
    
    doc.setFontSize(16);
    doc.setTextColor(0);
    doc.text(filteredOrders.length.toString(), 25, 68);
    doc.text(`P ${totalSales.toLocaleString()}`, 100, 68);

    // --- 4. DATA TABLE ---
    const tableColumn = ["Date", "Order ID", "Customer", "Type", "Payment", "Amount"];
    const tableRows = [];

    filteredOrders.forEach(order => {
      const orderData = [
        new Date(order.createdAt).toLocaleDateString(),
        order._id.substring(order._id.length - 6).toUpperCase(),
        order.contactInfo?.name || order.user?.name || 'Guest',
        order.orderType,
        order.paymentMethod,
        `P ${order.totalPrice.toLocaleString()}`
      ];
      tableRows.push(orderData);
    });

    // Add Footer Row to Table
    tableRows.push(['', '', '', '', { content: 'TOTAL', styles: { fontStyle: 'bold' } }, { content: `P ${totalSales.toLocaleString()}`, styles: { fontStyle: 'bold', textColor: [237, 108, 2] } }]);

    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: 85,
      theme: 'grid',
      headStyles: { fillColor: [237, 108, 2], textColor: 255 },
      columnStyles: {
          5: { halign: 'right' } // Right align amount
      },
      styles: { fontSize: 9 },
      didDrawPage: (data) => {
          // Footer Page Number
          doc.setFontSize(8);
          doc.setTextColor(150);
          doc.text(`Page ${doc.internal.getNumberOfPages()}`, 105, 290, null, null, "center");
      }
    });

    // Save File
    doc.save(`${branding.shortName.replace(/\s+/g, '_')}_Sales_Report_${startDate || 'All'}_to_${endDate || 'Now'}.pdf`);
  };

  return (
    <Container maxWidth="lg" sx={{ mt: 4, mb: 4 }}>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 4 }}>
        <Typography variant="h4" fontWeight="bold">Sales Reports</Typography>
        <Button 
            variant="contained" 
            color="primary"
            size="large"
            startIcon={<PictureAsPdfIcon />} 
            onClick={generatePDF}
            disabled={filteredOrders.length === 0}
            sx={{ fontWeight: 'bold' }}
        >
            Download PDF
        </Button>
      </Box>

      {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}

      {/* --- Summary Cards --- */}
      <Grid container spacing={3} sx={{ mb: 4 }}>
          <Grid item xs={12} md={4}>
              <Card sx={{ bgcolor: theme.palette.primary.light, boxShadow: 2 }}>
                  <CardContent>
                      <Typography color="text.secondary" gutterBottom fontWeight="bold">Total Revenue</Typography>
                      <Typography variant="h4" fontWeight="bold" color="primary">₱{totalSales.toLocaleString()}</Typography>
                  </CardContent>
              </Card>
          </Grid>
          <Grid item xs={12} md={4}>
              <Card sx={{ bgcolor: '#e3f2fd', boxShadow: 2 }}>
                  <CardContent>
                      <Typography color="text.secondary" gutterBottom fontWeight="bold">Total Transactions</Typography>
                      <Typography variant="h4" fontWeight="bold">{filteredOrders.length}</Typography>
                  </CardContent>
              </Card>
          </Grid>
          <Grid item xs={12} md={4}>
              <Card sx={{ bgcolor: '#f3e5f5', boxShadow: 2 }}>
                  <CardContent>
                      <Typography color="text.secondary" gutterBottom fontWeight="bold">Average Order Value</Typography>
                      <Typography variant="h4" fontWeight="bold">
                        ₱{filteredOrders.length > 0 ? (totalSales / filteredOrders.length).toLocaleString(undefined, {maximumFractionDigits:0}) : 0}
                      </Typography>
                  </CardContent>
              </Card>
          </Grid>
      </Grid>

      {/* --- Filters Section --- */}
      <Paper sx={{ p: 3, mb: 3, borderRadius: 2 }}>
          <Typography variant="subtitle1" fontWeight="bold" gutterBottom display="flex" alignItems="center">
            <DateRangeIcon sx={{ mr: 1 }}/> Date Range Configuration
          </Typography>
          
          <Stack direction={{ xs: 'column', md: 'row' }} spacing={2} alignItems="center">
              {/* Manual Inputs */}
              <TextField 
                type="date" 
                size="small"
                label="Start Date" 
                InputLabelProps={{ shrink: true }} 
                value={startDate}
                onChange={(e) => setStartDate(e.target.value)}
                inputProps={{ max: today }} // --- ITEM #24: DISABLE FUTURE DATES ---
              />
              <Typography>to</Typography>
              <TextField 
                type="date" 
                size="small"
                label="End Date" 
                InputLabelProps={{ shrink: true }} 
                value={endDate}
                onChange={(e) => setEndDate(e.target.value)}
                inputProps={{ max: today }} // --- ITEM #24: DISABLE FUTURE DATES ---
              />
              
              <Box sx={{ borderLeft: '1px solid #ddd', height: 30, mx: 2, display: { xs: 'none', md: 'block' } }} />

              {/* Quick Filters */}
              <Typography variant="body2" color="text.secondary">Quick Filters:</Typography>
              <Button size="small" variant="outlined" onClick={() => handleQuickFilter('today')}>Today</Button>
              <Button size="small" variant="outlined" onClick={() => handleQuickFilter('week')}>This Week</Button>
              <Button size="small" variant="outlined" onClick={() => handleQuickFilter('month')}>This Month</Button>
              <Button size="small" variant="outlined" onClick={() => handleQuickFilter('year')}>This Year</Button>
              
              <Button size="small" color="inherit" onClick={() => { setStartDate(''); setEndDate(''); }}>Reset</Button>
          </Stack>
      </Paper>

      {/* --- Data Table --- */}
      {loading ? <Box sx={{ display: 'flex', justifyContent: 'center', mt: 4 }}><CircularProgress /></Box> : (
        <TableContainer component={Paper} elevation={2} sx={{ borderRadius: 2 }}>
            <Table size="small">
                <TableHead sx={{ bgcolor: theme.palette.background.footer }}>
                    <TableRow>
                        <TableCell sx={{ fontWeight: 'bold', color: 'white' }}>Date</TableCell>
                        <TableCell sx={{ fontWeight: 'bold', color: 'white' }}>Order ID</TableCell>
                        <TableCell sx={{ fontWeight: 'bold', color: 'white' }}>Customer</TableCell>
                        <TableCell sx={{ fontWeight: 'bold', color: 'white' }}>Type</TableCell>
                        <TableCell sx={{ fontWeight: 'bold', color: 'white' }}>Payment</TableCell>
                        <TableCell align="right" sx={{ fontWeight: 'bold', color: 'white' }}>Amount</TableCell>
                    </TableRow>
                </TableHead>
                <TableBody>
                    {filteredOrders.length > 0 ? filteredOrders.map(order => (
                        <TableRow key={order._id} hover>
                            <TableCell>{new Date(order.createdAt).toLocaleDateString()}</TableCell>
                            <TableCell sx={{ fontFamily: 'monospace' }}>{order._id.substring(order._id.length - 6).toUpperCase()}</TableCell>
                            <TableCell>{order.contactInfo?.name || order.user?.name}</TableCell>
                            <TableCell>{order.orderType}</TableCell>
                            <TableCell>{order.paymentMethod}</TableCell>
                            <TableCell align="right">₱{order.totalPrice.toLocaleString()}</TableCell>
                        </TableRow>
                    )) : (
                        <TableRow>
                            <TableCell colSpan={6} align="center" sx={{ py: 3 }}>No sales records found for this period.</TableCell>
                        </TableRow>
                    )}
                    
                    {filteredOrders.length > 0 && (
                        <TableRow sx={{ bgcolor: theme.palette.primary.light }}>
                            <TableCell colSpan={5} align="right" sx={{ fontWeight: 'bold', fontSize: '1.1rem' }}>TOTAL SALES</TableCell>
                            <TableCell align="right" sx={{ fontWeight: 'bold', fontSize: '1.1rem', color: theme.palette.primary.main }}>
                                ₱{totalSales.toLocaleString()}
                            </TableCell>
                        </TableRow>
                    )}
                </TableBody>
            </Table>
        </TableContainer>
      )}
    </Container>
  );
}

export default AdminReportsPage;
